SELECT
				CASE
					WHEN LEN(CPR.PERSONNUMMER)= 9
					THEN '0'+ CONVERT(varchar, LEFT(CPR.PERSONNUMMER, 5))+'-'+ CONVERT(varchar, RIGHT(CPR.PERSONNUMMER, 4))
					WHEN LEN(CPR.PERSONNUMMER)= 10
					THEN CONVERT(varchar, LEFT(CPR.personnummer, 6)) + '-' + CONVERT(varchar, RIGHT(CPR.personnummer, 4))
				END AS CPR,
				CPR.KOMMUNENUMMER,
				CPR.FØDSEL_DATO AS Fødselsdato,
				CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) AS Alder,
				CASE
					WHEN CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) BETWEEN 0AND 5 Then '0 - 5 år'
					WHEN CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) BETWEEN 6 AND 16 Then '06 - 16 år'
					WHEN CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) BETWEEN 17 AND 24 Then '17 - 24 år'
					WHEN CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) BETWEEN 25 AND 44 Then '25 - 44 år'
					WHEN CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) BETWEEN 45 AND 64 Then '45 - 64 år'
					WHEN CONVERT(INT, DATEDIFF(d, CPR.FØDSEL_DATO, GETDATE()) / 365.25) > 64 Then 'Over 64 år'
				END AS Aldersklasse,
				CPR.KØN AS Køn,
				CPR.STILLING AS Stilling,
				CASE
					WHEN CPR.STILLING_DATO < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, CPR.STILLING_DATO, 120)
				END AS Stillingsdato,
				CAST(RTRIM(REVERSE(REPLACE(SUBSTRING(REVERSE(CPR.ADRESSERINGSNAVN), 1, CHARINDEX(',', REVERSE(CPR.ADRESSERINGSNAVN))), ',', ''))) + ' ' + REPLACE(SUBSTRING(CPR.ADRESSERINGSNAVN, 1, CHARINDEX(',', CPR.ADRESSERINGSNAVN)), ',', '') AS VARCHAR(60)) AS Navn,
				CASE
					WHEN CPR.ADRNAVN_DATO < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, CPR.ADRNAVN_DATO, 120)
 				END AS Dato_for_adresseringsnavn,
				CAST(RTRIM(ADGADR.VEJADRNAVN + ' ' + REPLACE(LTRIM(REPLACE(RTRIM(ADGADR.HUS_NR), '0', ' ')), ' ', '0') + ' ' + RTRIM(LTRIM(CPR.ETAGE)) + ' ' + RTRIM(LTRIM(CPR.SIDE_DØRNR))) AS VARCHAR(50)) AS Adresse,
				ADGADR.SUPBYNAVN AS Supplerende_bynavn,
				ADGADR.POSTNR,
				ADGADR.POSTBYNAVN,
				CAST(ADGADR.POSTNR AS VARCHAR (5))+' '+ADGADR.POSTBYNAVN AS Postdistrikt,
				ADGADR.BYGNAVN,
				CPR.FOLKEKIRK_TILH_MRK AS Folkekirkemarkering,
				CASE
					WHEN CPR.FOLKEKIRK_MRK_DATO < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
 					ELSE CONVERT(datetime, CPR.FOLKEKIRK_MRK_DATO, 120)
 				END AS Dato_for_folkekirkemarkering,
				CAST(QL58900V.TEKST AS VARCHAR(75)) AS Borgerstatus,
				CASE
					WHEN CPR.BORGERSTATUS_TS < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, substring(CPR.BORGERSTATUS_TS, 1, 10)  + ' ' + substring(CPR.BORGERSTATUS_TS, 12, 2) + ':' + substring(CPR.BORGERSTATUS_TS, 15, 2) + ':' + substring(CPR.BORGERSTATUS_TS, 18, 6), 120)
 				END AS Tidsstempling_borgerstatus,
				CPR.ANTAL_BØRN AS Antal_børn,
				CASE
					WHEN CPR.ADR_TILFLYT_TS < '1753-01-01'
					THEN CONVERT(datetime, '4713-12-31', 120)
 					WHEN CPR.ADR_TILFLYT_TS = '9999-12-31-00.00.00.000000' THEN CONVERT(datetime, '4713-12-31', 120) ELSE CONVERT(datetime, substring(CPR.ADR_TILFLYT_TS, 1, 10) + ' ' + substring(CPR.ADR_TILFLYT_TS, 12, 2) + ':' + substring(CPR.ADR_TILFLYT_TS, 15, 2) + ':' + substring(CPR.ADR_TILFLYT_TS, 18, 6), 120)
 				END AS Tidsstempling_tilflytning,
				CPR.VEJ_KODE AS Vejkode,
				CPR.HUS_NUMMER AS Husnummer_bogstav,
				CPR.ETAGE AS Etage,
				CPR.SIDE_DØRNR AS Side,
				CPR.BYGNING_NUMMER AS Bygningsnummer,
				CASE
					WHEN CPR.ADR_FRAFLYT_TS < CPR.ADR_TILFLYT_TS
					THEN CONVERT(datetime, '4713-12-31', 120)
 					WHEN CPR.ADR_FRAFLYT_TS < '1753-01-01'
 					THEN CONVERT(datetime, '1753-01-01', 120)
 					WHEN CPR.ADR_FRAFLYT_TS = '9999-12-31-00.00.00.000000'
 					THEN CONVERT(datetime, '4713-12-31', 120)
 					ELSE CONVERT(datetime, substring(CPR.ADR_FRAFLYT_TS,  1, 10) + ' ' + substring(CPR.ADR_FRAFLYT_TS, 12, 2) + ':' + substring(CPR.ADR_FRAFLYT_TS, 15, 2) + ':' + substring(CPR.ADR_FRAFLYT_TS, 18, 6), 120)
				END AS Tidsstempling_fraflytning,
				CPR.CO_NAVN AS CO_Navn,
				CASE
					WHEN CPR.KOM_TILFLYTDATO < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, CPR.KOM_TILFLYTDATO, 120)
				END AS Kommune_tilflytningsdato,
				CPR.FRAFLYT_KOMMUNENR AS Fraflytningskommunenummer,
				QL60000V.TEKST As Fraflytningskommune,
				CASE
					WHEN CPR.ADRESSE_BESKYTTELSE ='B'
					THEN 'Adressen er beskyttet i CPR'
					WHEN CPR.ADRESSE_BESKYTTELSE='L'
					THEN 'Adressen må ikke optages i vejvisere'
					ELSE 'Adressen er ikke beskyttet'
				END AS Adressebeskyttelse,
				CASE
					WHEN CPR.ADRESSEBESKYT_DATO < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, CPR.ADRESSEBESKYT_DATO, 120)
 				END AS Dato_for_adressebeskyttelse,
				CASE
					WHEN CPR.ADR_BESKYT_SLTDATO < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, CPR.ADR_BESKYT_SLTDATO, 120)
				END AS Dato_sletning_adressebeskyt,
				CASE
					WHEN CPR.CIVILSTAND_TS < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
 					ELSE CONVERT(datetime, substring(CPR.CIVILSTAND_TS, 1, 10) + ' ' + substring(CPR.CIVILSTAND_TS, 12, 2) + ':' + substring(CPR.CIVILSTAND_TS, 15, 2) + ':' + substring(CPR.CIVILSTAND_TS, 18, 6), 120)
 				END AS Tid_for_civilstand,
				CAST(QL58800V.TEKST AS VARCHAR(75)) AS Civilstand,
				CASE
					WHEN CPR.CIVILST_OPHØR_TS < '1753-01-01'
					THEN CONVERT(datetime,  '1753-01-01', 120)
					WHEN CPR.CIVILST_OPHØR_TS = '9999-12-31-00.00.00.000000'
					THEN CONVERT(datetime, '4713-12-31', 120)
					ELSE CONVERT(datetime,  substring(CPR.CIVILST_OPHØR_TS, 1, 10) + ' ' + substring(CPR.CIVILST_OPHØR_TS, 12, 2) + ':' + substring(CPR.CIVILST_OPHØR_TS, 15, 2) + ':' + substring(CPR.CIVILST_OPHØR_TS, 18, 6), 120)
				END AS Tid_for_civilstandsophør,
				CPR.PERSONNR_ÆGTEFÆLLE AS Personnummer_ægtefælle,
				CPR.ÆGTEFÆLLE_FLAG AS Flag_for_ægtefælle,
				CASE
					WHEN	CPR.EJ_UMYNDIGGØR_FLAG <> 1
					THEN 'Ja'
					ELSE 'Nej'
				END AS Umyndiggjort,
				CPR.LAND_KODE AS Landekode,
				CAST(QL59400V.TEKST AS VARCHAR(75)) AS Land,
				CASE
					WHEN CPR.STATSB_RET_TS < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					ELSE CONVERT(datetime, substring(CPR.STATSB_RET_TS, 1, 10) + ' ' + substring(CPR.STATSB_RET_TS, 12, 2) + ':' + substring(CPR.STATSB_RET_TS, 15, 2) + ':' + substring(CPR.STATSB_RET_TS, 18, 6), 120)
				END AS Tid_for_ændr_statsborgerskab,
				CASE
					WHEN CPR.STATBORG_OPHØR_TS < '1753-01-01'
					THEN CONVERT(datetime, '1753-01-01', 120)
					WHEN CPR.STATBORG_OPHØR_TS = '9999-12-31-00.00.00.000000'
					THEN CONVERT(datetime, '4713-12-31', 120)
					ELSE CONVERT(datetime,  substring(CPR.STATBORG_OPHØR_TS, 1, 10) + ' ' + substring(CPR.STATBORG_OPHØR_TS, 12, 2) + ':' + substring(CPR.STATBORG_OPHØR_TS, 15, 2) + ':' + substring(CPR.STATBORG_OPHØR_TS, 18, 6), 120)
				END AS Tid_for_ophør_statsborgersk,
				CPR.PERSONNUMMER_MOR,
				CPR.PERSONNUMMER_FAR,
				CPR.MOR_DOK,
				CPR.FAR_DOK,
				CPR.BORGERSTATUS_UM AS Usik_tidstempel_borgerstatus,
				CAST(CPR.KOMMUNENUMMER AS VARCHAR(3)) + RIGHT('0000' + CONVERT(VARCHAR, CPR.VEJ_KODE), 4) + RTRIM(CPR.HUS_NUMMER) AS ADRESSELINK_ID,
				CAST(CPR.KOMMUNENUMMER AS VARCHAR(3)) + CAST(CPR.VEJ_KODE AS VARCHAR(4)) + RTRIM(CPR.HUS_NUMMER) AS ADRESSE_ID,
				CAST(CPR.KOMMUNENUMMER AS VARCHAR(3)) + CAST(CPR.VEJ_KODE AS VARCHAR(4)) + RTRIM(CPR.HUS_NUMMER) + LTRIM(CPR.ETAGE) + LTRIM(CPR.SIDE_DØRNR) AS UDVadresseID,
				CPR.PERSONNUMMER,
				JY73200V.KOOROEST,
				JY73200V.KOORNORD,
				JY73200V.DDKNCELLE100M,
				JY73200V.DDKNCELLE1KM,
				JY73200V.DDKNCELLE10KM
FROM
				QL59400V RIGHT OUTER JOIN
        AA70000T AS CPR INNER JOIN
        JN67100T ON CPR.KOMMUNENUMMER = JN67100T.KOMMUNENUMMER LEFT OUTER JOIN
        QL58900V ON CPR.BORGERSTATUS_KODE = QL58900V.KODE LEFT OUTER JOIN
        QL58800V ON CPR.CIVILSTAND = QL58800V.KODE ON QL59400V.KODE = CPR.LAND_KODE LEFT OUTER JOIN
        QL60000V ON CPR.FRAFLYT_KOMMUNENR = QL60000V.KODE LEFT OUTER JOIN
        JY72000V AS ADGADR LEFT OUTER JOIN
        JY73200V ON ADGADR.APU_ID = JY73200V.APU_ID ON CPR.KOMMUNENUMMER = ADGADR.KOMMUNENUMMER AND
        CPR.VEJ_KODE = ADGADR.VEJKODE AND CPR.HUS_NUMMER = ADGADR.HUS_NR
WHERE        (CPR.BORGERSTATUS_KODE < 10)
