SELECT
				FLIS_Medarbejder_Ansaettelse.OBJECTID,
				FLIS_Medarbejder_Ansaettelse.KommuneNummer,
				FLIS_Medarbejder_Ansaettelse.InstitutionsNummer,
				FLIS_Medarbejder_Ansaettelse.Tidspunkt,
				FLIS_Medarbejder_Ansaettelse.PersonaleNummer,
				FLIS_Medarbejder_Ansaettelse.PersonNummer,
				LEFT(FLIS_Medarbejder_Ansaettelse.PersonNummer,6) + '-' + RIGHT(FLIS_Medarbejder_Ansaettelse.PersonNummer,4) AS CPR,
				FLIS_Medarbejder_Ansaettelse.Navn,
				FLIS_Medarbejder_Ansaettelse.Foedselsdato,
				FLIS_Medarbejder_Ansaettelse.Alder,
				FLIS_Medarbejder_Ansaettelse.Koen,
				CAST(FLIS_Medarbejder_Ansaettelse.CivilstandStatus AS VARCHAR(23)) AS CivilstandStatus,
				FLIS_Medarbejder_Ansaettelse.AnsaettelsesDato,
				FLIS_Medarbejder_Ansaettelse.AnsaettelsesStopDato,
				FLIS_Medarbejder_Ansaettelse.Anciennitet,
				FLIS_Medarbejder_Ansaettelse.StillingsKode,
				FLIS_Medarbejder_Ansaettelse.StillingsNavn,
				FLIS_Medarbejder_Ansaettelse.StillingsKategoriKode,
				FLIS_Medarbejder_Ansaettelse.StillingsKategori,
				FLIS_Medarbejder_Ansaettelse.AnsaettelseStatusKode_FS,
				CAST(FLIS_Medarbejder_Ansaettelse.AnsaettelseStatusNavn_FS AS VARCHAR(50)) AS AnsaettelseStatusNavn_FS,
				FLIS_Medarbejder_Ansaettelse.AnsaettelsesFormKode,
				CAST(FLIS_Medarbejder_Ansaettelse.AnsaettelsesForm AS VARCHAR(23)) AS AnsaettelsesForm,
				FLIS_Medarbejder_Ansaettelse.AnsaettelsesStatusKode,
				CAST(FLIS_Medarbejder_Ansaettelse.AnsaettelsesStatus AS VARCHAR(24)) AS AnsaettelsesStatus,
				FLIS_Medarbejder_Ansaettelse.AfloeningFormNummer,
				CAST(FLIS_Medarbejder_Ansaettelse.AfloeningFormNavn AS VARCHAR(15)) AS AfloeningFormNavn,
				CAST(FLIS_Medarbejder_Ansaettelse.AfloeningKategoriNavn AS VARCHAR(13)) AS AfloeningKategoriNavn,
				FLIS_Medarbejder_Ansaettelse.LoenKlasseNummer,
				FLIS_Medarbejder_Ansaettelse.LoenKlasseNavn,
				FLIS_Medarbejder_Ansaettelse.OverenskomstNummer,
				FLIS_Medarbejder_Ansaettelse.OverenskomstNavn,
				FLIS_Medarbejder_Ansaettelse.OverenskomstOmraade,
				FLIS_Medarbejder_Ansaettelse.Kvote,
				FLIS_Medarbejder_Ansaettelse.Udenfravaer6maaneder,
				FLIS_Medarbejder_Ansaettelse.LangtidsFrisk,
				FLIS_Medarbejder_Ansaettelse.DimMedarbejder,
				FLIS_Medarbejder_Ansaettelse.DimAutoriseretKontoplan,
				CAST(DimAutoriseretKontoplan.Hovedartsnavn AS VARCHAR(10)) AS Hovedartsnavn,
				FLIS_Medarbejder_Ansaettelse.DimUdvidetkontoplan,
				CAST(DimUdvidetKontoplan.Funktion1Navn AS VARCHAR(45)) AS Funktion1Navn,
				CAST(DimUdvidetKontoplan.Funktion2Navn AS VARCHAR(50)) AS Funktion2Navn,
				CAST(DimUdvidetKontoplan.Funktion3Navn AS VARCHAR(60)) AS Funktion3Navn,
				CAST(DimUdvidetKontoplan.Omkostningssted1Navn AS VARCHAR(23)) AS Omkostningssted1Navn,
				CAST(DimUdvidetKontoplan.Gruppering1Navn AS VARCHAR(23)) AS Gruppering1Navn,
				CAST(DimUdvidetKontoplan.Art1Navn AS VARCHAR(10)) AS Art1Navn,
				CAST(DimUdvidetKontoplan.Art2Navn AS VARCHAR(10)) AS Art2Navn,
				FLIS_Medarbejder_Ansaettelse.DimOpusKapitalmiddel,
				CAST(DimOpusKapitalmiddel.KapitalmiddelNiv2Navn AS VARCHAR(31)) AS KapitalmiddelNiv21Navn,
				CAST(DimOpusKapitalmiddel.KapitalmiddelNiv4Navn AS VARCHAR(40)) AS KapitalmiddelNiv4Navn,
				CAST(DimOpusKapitalmiddel.KapitalmiddelNiv5Navn AS VARCHAR(40)) AS KapitalmiddelNiv5Navn,
				FLIS_Medarbejder_Ansaettelse.DimOpusOmkostningssted,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv2Navn AS VARCHAR(23)) AS OmkostningsstedNiv2Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv3Navn AS VARCHAR(35)) AS OmkostningsstedNiv3Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv4Navn AS VARCHAR(40)) AS OmkostningsstedNiv4Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv5Navn AS VARCHAR(40)) AS OmkostningsstedNiv5Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv6Navn AS VARCHAR(40)) AS OmkostningsstedNiv6Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv7Navn AS VARCHAR(40)) AS OmkostningsstedNiv7Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv8Navn AS VARCHAR(40)) AS OmkostningsstedNiv8Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv9Navn AS VARCHAR(40)) AS OmkostningsstedNiv9Navn,
				CAST(DimOpusOmkostningssted.OmkostningsstedNiv10Navn AS VARCHAR(40)) AS OmkostningsstedNiv10Navn,
				FLIS_Medarbejder_Ansaettelse.DimOpusProfitCenter,
				CAST(DimOpusProfitcenter.ProfitcenterNiv2Navn AS VARCHAR(17)) AS ProfitcenterNiv2Navn,
				CAST(DimOpusProfitcenter.ProfitcenterNiv3Navn AS VARCHAR(40)) AS ProfitcenterNiv3Navn,
				CAST(DimOpusProfitcenter.ProfitcenterNiv4Navn AS VARCHAR(40)) AS ProfitcenterNiv4Navn,
				CAST(DimOpusProfitcenter.ProfitcenterNiv5Navn AS VARCHAR(40)) AS ProfitcenterNiv5Navn,
				CAST(DimOpusProfitcenter.ProfitcenterNiv6Navn AS VARCHAR(40)) AS ProfitcenterNiv6Navn,
				CAST(DimOpusProfitcenter.ProfitcenterNiv7Navn AS VARCHAR(40)) AS ProfitcenterNiv7Navn,
				CAST(DimOpusProfitcenter.ProfitcenterNiv8Navn AS VARCHAR(40)) AS ProfitcenterNiv8Navn,
				FLIS_Medarbejder_Ansaettelse.MI_PRINX,
				CAST(FLIS_Medarbejder_Ansaettelse.MI_STYLE AS VARCHAR(40)) AS MI_STYLE
FROM
				FLIS_Medarbejder_Ansaettelse INNER JOIN
				DimUdvidetKontoplan ON FLIS_Medarbejder_Ansaettelse.DimUdvidetkontoplan = DimUdvidetKontoplan.DimUdvidetKontoplanID LEFT OUTER JOIN
				DimOpusKapitalmiddel ON FLIS_Medarbejder_Ansaettelse.DimOpusKapitalmiddel = DimOpusKapitalmiddel.DimOpusKapitalmiddelID LEFT OUTER JOIN
				DimOpusProfitcenter ON FLIS_Medarbejder_Ansaettelse.DimOpusProfitCenter = DimOpusProfitcenter.DimOpusProfitcenterID LEFT OUTER JOIN
				DimAutoriseretKontoplan ON
				FLIS_Medarbejder_Ansaettelse.DimAutoriseretKontoplan = DimAutoriseretKontoplan.DimAutoriseretKontoplanID LEFT OUTER JOIN
				DimOpusOmkostningssted ON FLIS_Medarbejder_Ansaettelse.DimOpusOmkostningssted = DimOpusOmkostningssted.DimOpusOmkostningsstedID