SELECT
				GS_BORGER_FLYTNING.Bopælskommunenr,
				GS_BORGER_FLYTNING.Bopælskommune,
				GS_BORGER_FLYTNING.PERSONNUMMER,
				GS_BORGER_FLYTNING.CPR,
				GS_BORGER_FLYTNING.Fødselsdato,
				GS_BORGER_FLYTNING.Alder,
				GS_BORGER_FLYTNING.Navn,
				GS_BORGER_FLYTNING.CO_NAVN,
				GS_BORGER_FLYTNING.Adresse,
				GS_BORGER_FLYTNING.Supplerende_bynavn,
				GS_BORGER_FLYTNING.Postnummer,
				GS_BORGER_FLYTNING.Bynavn,
				GS_BORGER_FLYTNING.Postdistrikt,
				GS_BORGER_FLYTNING.Tilflytningsdato,
				GS_BORGER_FLYTNING.Borgerstatus,
				GS_BORGER_FLYTNING.Borgerstatuskode,
				GS_BORGER_FLYTNING.Landekode,
				GS_BORGER_FLYTNING.Land,
				GS_BORGER_FLYTNING.ADRESSELINK_ID,
				GS_BORGER_FLYTNING.ADRESSE_ID,
				GS_BORGER_FLYTNING.UDVadresseID,
				GS_BORGER_FLYTNING.PERSONNUMMER_MOR,
				GS_BORGER_FLYTNING.PERSONNUMMER_FAR
FROM
				GS_BORGER_FLYTNING INNER JOIN
				(Select CPR, MAX(Tilflytningsdato) AS Tilflytningsdato
				FROM
				GS_BORGER_FLYTNING AS GS_BORGER_FLYTNING_1
				GROUP BY CPR) AS maxdato ON GS_BORGER_FLYTNING.CPR = maxdato.CPR AND
				GS_BORGER_FLYTNING.Tilflytningsdato = maxdato.Tilflytningsdato
WHERE
				(GS_BORGER_FLYTNING.Borgerstatuskode < 30)